
name: Rust PR

# Run on pushes to master, and on all pull requests.
on:
  push:
    branches:
    - master
  pull_request: {}


jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          # Install a "minimal" rust toolchain (without docs, etc)
          toolchain: stable
          profile: minimal
          override: true
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check --all --examples --tests --benches

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          # Install a "minimal" rust toolchain (without docs, etc), but 
          # include rustfmt.  
          toolchain: stable
          profile: minimal 
          override: true
          components: rustfmt 
      - name: Run rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt --all -- --check
